fprintf("Gaussian Kernel:\n");
C = 1; sigma = 0.0001;
model= svmTrain(Xtrain, Ytrain, C, @(x1, x2) gaussianKernel(x1, x2, sigma));
GaussianPreds = predictGaussianSVM(model,Xtest);
iswrong = ~(GaussianPreds==Ytest);
misclassrategauss = sum(iswrong)/numel(iswrong);
confusionchart(Ytest,GaussianPreds,"RowSummary","row-normalized");
EvalGauss = evaluate(Ytest,GaussianPreds);
fprintf("Confusion Matrix=\n");
disp(EvalGauss.cfm);
fprintf("Precision=");
disp(EvalGauss.precision);
fprintf("Recall=");
disp(EvalGauss.recall);
fprintf("Accuracy=");
disp(EvalGauss.accuracy*100);