
subplot(3,3,1);
gscatter(training_data.clumpthickness,training_data.class);
subplot(3,3,2);
gscatter(training_data.uniformcellsize,training_data.class);
subplot(3,3,3);
gscatter(training_data.uniformcellshape,training_data.class);
subplot(3,3,4);
gscatter(training_data.margadhesion,training_data.class);
subplot(3,3,5);
gscatter(training_data.epithelial,training_data.class);
subplot(3,3,6);
gscatter(training_data.barenuclei,training_data.class);
subplot(3,3,7);
gscatter(training_data.blandchromatin,training_data.class);
subplot(3,3,8);
gscatter(training_data.normalnucleoli,training_data.class);
subplot(3,3,9);
gscatter(training_data.mitoses,training_data.class);
